adding John's requested bit

diff --git a/.github/workflows/calculate-version.yml b/.github/workflows/calculate-version.yml
--- a/.github/workflows/calculate-version.yml
+++ b/.github/workflows/calculate-version.yml
@@ -46,3 +46,4 @@ jobs:
           NEW_VERSION_TAG=$(oe version -i -b $GITHUB_HEAD_REF) && export NEW_VERSION_TAG
           echo "new version: $NEW_VERSION_TAG"
           echo "version=$NEW_VERSION_TAG" >> $GITHUB_OUTPUT
+          if [[ -z "${GITHUB_OUTPUT}" ]]; then echo "GITHUB_OUTPUT zero length or unset! Aborting"; exit 1; fi
diff --git a/major-version-tag/action.yml b/major-version-tag/action.yml
--- a/major-version-tag/action.yml
+++ b/major-version-tag/action.yml
@@ -16,4 +16,5 @@ runs:
         MAJOR_VERSION=(${version//./ })
         echo "major version is $MAJOR_VERSION"
         echo "major_version=$MAJOR_VERSION" >> $GITHUB_OUTPUT
+        if [[ -z "${GITHUB_OUTPUT}" ]]; then echo "GITHUB_OUTPUT zero length or unset! Aborting"; exit 1; fi
       shell: bash
